Preliminary Documentation
MountainBuffalo/Cacher pull request #13
Opened 2017-05-28 21:32 UTC by RlonRyan

This is a test of how to document the code. I am not on my mac right now
so I'm not entirely certain if this is 100% correct or if it has the
correct formatting. Regardless, this can serve as a starting point in
developing the method by which we want to document the code.

2017-05-28 21:56 UTC, RlonRyan commented on Cacher/Cache.swift
> +    ///
Should be using `/** ... */` form instead.

2017-05-28 22:39 UTC, jay18001 commented on Cacher/Cache.swift
> +    ///
Use `///` just remove the empty lines

2017-05-29 01:18 UTC, jay18001 requested changes
Single Line comments should use /// and multiline ones use /** ... */. We don't need the empty spaces above and below.

2017-05-29 03:08 UTC, RlonRyan commented
I'm just gonna close this one and start over later from scratch.

2017-05-29 03:08 UTC, closed without merging